### ISSUE TITLE
Update or remove revision script

### ISSUE THREAD

**Issue by bradh** [opticks-org/opticks#2]
https://github.com/opticks-org/opticks/blob/master/Code/update-build-revision.py is subversion based.

**Comment by dwcaraway** [comment]
This script runs the [svnversion command](http://svnbook.red-bean.com/en/1.7/svn.ref.svnversion.re.html) and saves the output to `Code/application/Utilities/BuildRevision.h` which is currently untracked but not on `.gitignore`. The output is not meaningful with git.

Looks like it's referenced in a few files, don't have visual studio on my mac so can't confirm yet if `BuildRevision.h` is necessary to compile / run.

```bash
$ git grep --name-only "BuildRevision.h"
/* output 
Code/application/Utilities/ConfigurationSettingsImp.cpp
Code/application/Utilities/Utilities.vcxproj
Code/application/Utilities/Utilities.vcxproj.filters
Code/build.py
Code/update-build-revision.py
*/

**Comment by bradh** [comment]
I'd imagine you'd want to grab a git_id value.

**Comment by tclarke** [comment]
I haven't done any conversions from the svn codebase yet. It is there to publish a SCM rev in the About dialog so a git ID is the correct thing to add. This weekend I plan on updating the CMake build and will incorporate a solution to this as part of the fix. If you run the script and you don't have a subversion working copy it will just insert "Unknown" into the file.

**Comment by dwcaraway** [comment]
What about the [git describe](https://git-scm.com/docs/git-describe) output? Below is result of running the command on `master`:

```
$ git describe
v4.12.0rc1-16-g99b6f72d
```
This indicates that `HEAD` has a latest tag `v4.12.0rc1`, that we've had `16` commits since then and that the SHA1 hash is `99b6f72d` which corresponds to 

```
$ git rev-parse --short HEAD
99b6f72d
```
If there are no commits since the last tag (e.g. an official release build ), then the output would just be the tag name.

```
$ git checkout v4.12.0rc1
$ git describe
// v4.12.0rc1
```

There are chances of collisions with history rewrites but given this identifier on a deployed instance, you'd be able to tell what they're running.

**Comment by tclarke** [comment]
Describe isn't quite correct as the rev tag is used to build a full version which will be something like 4.13.0dev1-99b7f72. rev-parse is likely the correct answer.
