### ISSUE TITLE
Targeted Platforms

### ISSUE THREAD

**Issue by dwcaraway** [opticks-org/opticks#6]
Currently, Opticks has instructions for Windows and Solaris. What are the targeted platforms now? 

- [ ] Windows 7/10
- [ ] Mac
- [ ] Linux

**Comment by tclarke** [comment]
Solaris has not been supported for a few revs. The build instructions are essentially the same for Linux which is why they are still there (renaming the files wasn't a high priority so they still say Solaris). I have tried to port to OSX but there are some non-trivial issues that need to be addressed. I do plan on looking into it after the next bugfix release (my laptop is a mac so I have an interest in it). I believe the 3 you list are the sensible targets moving forward. I don't want to do any ports until the CMake changes are in as it vasty simplifies dependency management. We currently have pre-built deps on opticks.org for windows and linux that need to be used...adding mac or updating them requires a requild of dozens of libraries even if native versions are available. The current system makes it easier to work with Windows builds and ensures consistent versions of third party libraries (important for the government users who need to get explicit approval for each version change of a library).

**Comment by dwcaraway** [comment]
Cool, support for all three sounds good, from mailing list, sounds like RHEL/Centos and also Debian (ubuntu) for Linux would be nice.

**Comment by tclarke** [comment]
Probably a combination of travis and AWS CodeBuild (for windows). travis would do unit tests for linux/osx. CodeBuild would only be used for rc and release builds.
